### ISSUE TITLE
LO SPECIALE DI NATALE È STATO RENDERIZZATO????????

### ISSUE THREAD

**Issue by emilianomaccaferri** [SnowyCoder/cg23-voxelrenderer#1]

**Comment by SnowyCoder** [comment]
RENDERIZZATO, POSSIAMO PROCEDERE A DENUNCIARE BABBO NATALE!!!!!!!
![image](https://github.com/SnowyCoder/cg23-voxelrenderer/assets/10945206/3fe1f8f2-1ff4-499c-8a93-34b62ad5747f)
